services:
  mitmproxy-transparent:
    restart: always
    image: mitmproxy/mitmproxy
    command:
      [
        "mitmdump",
        "-v",
        "--upstream-auth=${PROXY_AUTH}",
        "--mode=upstream:http://mitmproxy:8080",
        "--showhost",
        "--ssl-insecure",
      ]
    volumes:
      - "./certs/:/home/mitmproxy/.mitmproxy/"
    ports:
      - "8443:8080"

  mitmproxy:
    restart: always
    image: mitmproxy/mitmproxy
    command:
      ["mitmdump", "-v", "--proxyauth=${PROXY_AUTH}", "--ignore", "${IGNORE}"]
    volumes:
      - "./certs/:/home/mitmproxy/.mitmproxy/"
    ports:
      - "8080:8080"
